nodeLinker: node-modules

packageExtensions:
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": ^7.18.9
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": ^7.18.9
  "@dnd-kit/modifiers@*":
    peerDependencies:
      react: ^16.14.0
  "@figspec/react@*":
    dependencies:
      react: ^16.14.0
  "@phenomnomnominal/tsquery@*":
    dependencies:
      typescript: 4.7.4
  "@storybook/addon-docs@*":
    dependencies:
      # react-is: "*"
      "@babel/core": ^7.18.9
      webpack: ^5.75.0
  "@storybook/core-common@*":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  "@storybook/docs-tools@*":
    dependencies:
      react: ^16.14.0
      react-dom: ^16.14.0
  ts-node@*:
    dependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
