nodeLinker: node-modules

packageExtensions:
  "@dnd-kit/modifiers@*":
    peerDependencies:
      react: ^16.14.0
  "@figspec/react@*":
    dependencies:
      react: ^16.14.0
  "@geometricpanda/storybook-addon-badges@*":
    dependencies:
      "@storybook/addons": ^7.0.0-rc.4
      "@storybook/api": ^7.0.0-rc.4
      "@storybook/components": ^7.0.0-rc.4
      "@storybook/core-events": ^7.0.0-rc.4
      "@storybook/theming": ^7.0.0-rc.4
  "@phenomnomnominal/tsquery@*":
    dependencies:
      typescript: 4.9.5
  "@stylelint/postcss-css-in-js@*":
    dependencies:
      postcss-syntax: ^0.36.2
  ts-node@*:
    dependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
