nodeLinker: node-modules

packageExtensions:
  '@dnd-kit/modifiers@*':
    peerDependencies:
      react: ^18.2.0
  '@geometricpanda/storybook-addon-badges@*':
    dependencies:
      '@storybook/addons': ^7.0.12
      '@storybook/api': ^7.0.12
      '@storybook/components': ^7.0.12
      '@storybook/core-events': ^7.0.12
      '@storybook/theming': ^7.0.12
      '@storybook/manager-api': ^7.0.12
      '@storybook/preview-api': ^7.0.12
      '@storybook/types': ^7.0.12
  '@phenomnomnominal/tsquery@*':
    dependencies:
      typescript: ^5.0.4
  ts-node@*:
    dependencies:
      '@types/node': '*'
  storybook-addon-designs@*:
    dependencies:
      '@storybook/addons': ^7.0.12
      '@storybook/api': ^7.0.12
      '@storybook/theming': ^7.0.12
  rollup-plugin-auto-external@*:
    dependencies:
      rollup: ^3.19.1
  postcss-styled-syntax@*:
    dependencies:
      postcss: ^8.4.21

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
