nodeLinker: node-modules

packageExtensions:
  '@dnd-kit/modifiers@*':
    peerDependencies:
      react: ^16.14.0
  '@figspec/react@*':
    dependencies:
      react: ^16.14.0
  '@geometricpanda/storybook-addon-badges@*':
    dependencies:
      '@storybook/addons': ^7.0.5
      '@storybook/api': ^7.0.5
      '@storybook/components': ^7.0.5
      '@storybook/core-events': ^7.0.5
      '@storybook/theming': ^7.0.5
      '@storybook/blocks': ^7.0.5
      '@storybook/manager-api': ^7.0.5
      '@storybook/preview-api': ^7.0.5
      '@storybook/types': ^7.0.5
  '@phenomnomnominal/tsquery@*':
    dependencies:
      typescript: ^5.0.4
  '@stylelint/postcss-css-in-js@*':
    dependencies:
      postcss-syntax: ^0.36.2
  ts-node@*:
    dependencies:
      '@types/node': '*'
  storybook-addon-designs@*:
    dependencies:
      '@storybook/addons': ^7.0.5
      '@storybook/api': ^7.0.5
      '@storybook/theming': ^7.0.5
  rollup-plugin-auto-external@*:
    dependencies:
      rollup: ^3.19.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
