export const SSCIconNames = {
  angleDown: 'angle-down',
  angleLeft: 'angle-left',
  angleRight: 'angle-right',
  anglesRight: 'angles-right',
  angleUp: 'angle-up',
  arrowUp: 'arrow-up',
  backwardStep: 'backward-step',
  ban: 'ban',
  banLight: 'ban-light',
  calendar: 'calendar',
  check: 'check',
  checkCircle: 'check-circle',
  checkCircleSolid: 'check-circle-solid',
  checkCircleLight: 'check-circle-light',
  cog: 'cog',
  columns3: 'columns-3',
  compress: 'compress',
  copy: 'copy',
  ellipsisH: 'ellipsis-h',
  ellipsisV: 'ellipsis-v',
  error: 'error',
  errorCircle: 'error-circle',
  exclCircleLight: 'excl-circle-light',
  exclTriangle: 'excl-triangle',
  exclTriangleLight: 'excl-triangle-light',
  exclTriangleSolid: 'excl-triangle-solid',
  expand: 'expand',
  eye: 'eye',
  eyeSlash: 'eye-slash',
  filter: 'filter',
  gripDotsVertical: 'grip-dots-vertical',
  gripLines: 'grip-lines',
  infoCircle: 'info-circle', // rename to infoCircleSolid, used in platform
  infoCircleOutline: 'info-circle-outline', // rename to infoCircle, used in platform
  lightbulb: 'lightbulb',
  longArrowLeft: 'long-arrow-left',
  longArrowRight: 'long-arrow-right',
  minus: 'minus',
  plus: 'plus',
  quoteSquare: 'quote-square', // unused in DS, custom composition of icons, used in platform (replace with square-quote)
  resize: 'resize', // custom, does not have FA variant
  search: 'search',
  sitemap: 'sitemap',
  sort: 'sort',
  sortDown: 'sort-down',
  sortUp: 'sort-up',
  thumbtack: 'thumbtack',
  times: 'times',
  upload: 'upload',
  wrench: 'wrench', // custom, does not have FA variant
  company: 'company', // custom, does not have FA variant
} as const;

export const IconTypes = {
  ssc: 'ssc',
  far: 'far',
  fal: 'fal',
  fab: 'fab',
} as const;
