export const SSCIconNames = {
  wrench: 'wrench',
  chevronRight: 'chevron-right',
  eye: 'eye',
  eyeSlash: 'eye-slash',
  check: 'check',
  times: 'times',
  chevronDown: 'chevron-down',
  arrowUp: 'arrow-up',
  quoteSquare: 'quote-square',
  caretDown: 'caret-down',
  plus: 'plus',
  sort: 'sort',
  sortUp: 'sort-up',
  sortDown: 'sort-down',
  search: 'search',
  filter: 'filter',
  minus: 'minus',
  cog: 'cog',
  reorder: 'reorder',
  sitemap: 'sitemap',
  longArrowLeft: 'long-arrow-left',
  longArrowRight: 'long-arrow-right',
  ellipsisH: 'ellipsis-h',
  timesSolid: 'times-solid',
  banSolid: 'banSolid',
  exclTriangleSolid: 'excl-triangle-solid',
  infoCircle: 'info-circle',
  checkCircle: 'check-circle',
  error: 'error',
  exclTriangle: 'excl-triangle',
  ban: 'ban',
  lock: 'lock',
  checkCircleSolid: 'check-circle-solid',
  errorSolid: 'error-solid',
  ellipsisV: 'ellipsis-v',
  certifiedBadge: 'certified-badge',
  certifiedBadgeSolid: 'certified-badge-solid',
  upload: 'upload',
} as const;

export const IconTypes = {
  ssc: 'ssc',
} as const;
