export const ColorTypes = {
  primary50: 'primary.50',
  primary200: 'primary.200',
  primary400: 'primary.400',
  primary500: 'primary.500',
  primary600: 'primary.600',
  primary700: 'primary.700',
  neutral0: 'neutral.0',
  neutral100: 'neutral.100',
  neutral200: 'neutral.200',
  neutral300: 'neutral.300',
  neutral400: 'neutral.400',
  neutral500: 'neutral.500',
  neutral600: 'neutral.600',
  neutral700: 'neutral.700',
  neutral800: 'neutral.800',
  neutral900: 'neutral.900',
  neutral1000: 'neutral.1000',
  info50: 'info.50',
  info500: 'info.500',
  success50: 'success.50',
  success100: 'success.100',
  success500: 'success.500',
  success600: 'success.600',
  success700: 'success.700',
  warning50: 'warning.50',
  warning100: 'warning.100',
  warning500: 'warning.500',
  error50: 'error.50',
  error100: 'error.100',
  error500: 'error.500',
  error600: 'error.600',
  error700: 'error.700',
  gradeA: 'grade.A',
  gradeB: 'grade.B',
  gradeC: 'grade.C',
  gradeD: 'grade.D',
  gradeF: 'grade.F',
  kiwi: 'deprecated.kiwi',
  banana: 'deprecated.banana',
  pumpkin: 'deprecated.pumpkin',
  pumpkin0: 'deprecated.pumpkin0',
  strawberry: 'deprecated.strawberry',
  strawberry0: 'deprecated.strawberry0',
  cherry: 'deprecated.cherry',
  blueberryClassic: 'primary.500',
  radiantBlueberry: 'primary.400',
  dietBlueberry: 'primary.200',
  blueberry0: 'primary.50',
  eucalyptusClassic: 'deprecated.eucalyptusClassic',
  radiantEucalyptus: 'deprecated.radiantEucalyptus',
  dietEucalyptus: 'deprecated.dietEucalyptus',
  eucalyptus0: 'deprecated.eucalyptus0',
  graphite5B: 'neutral.1000',
  graphite4B: 'neutral.900',
  graphite3B: 'neutral.800',
  graphite2B: 'neutral.700',
  graphiteB: 'neutral.600',
  graphiteHB: 'neutral.500',
  graphiteH: 'neutral.400',
  graphite2H: 'neutral.300',
  graphite3H: 'neutral.200',
  graphite4H: 'neutral.100',
  graphite5H: 'neutral.0',
  severityInformational: 'serverity.informational',
  severityPositive: 'serverity.positive',
  severityLow: 'serverity.low',
  severityMedium: 'serverity.medium',
  severityHigh: 'serverity.high',
} as const;

export const DeprecatedColorTypes = [
  'kiwi',
  'banana',
  'pumpkin',
  'pumpkin0',
  'strawberry0',
  'strawberry0',
  'cherry',
  'blueberryClassic',
  'radiantBlueberry',
  'dietBlueberry',
  'blueberry0',
  'eucalyptusClassic',
  'radiantEucalyptus',
  'dietEucalyptus',
  'eucalyptus0',
  'graphite5B',
  'graphite4B',
  'graphite3B',
  'graphite2B',
  'graphiteB',
  'graphiteHB',
  'graphiteH',
  'graphite2H',
  'graphite3H',
  'graphite4H',
  'graphite5H',
] as const;
