export const ColorTypes = {
  kiwi: 'kiwi',
  banana: 'banana',
  pumpkin: 'pumpkin',
  pumpkin0: 'pumpkin0',
  strawberry: 'strawberry',
  strawberry0: 'strawberry0',
  cherry: 'cherry',
  blueberryClassic: 'blueberryClassic',
  radiantBlueberry: 'radiantBlueberry',
  dietBlueberry: 'dietBlueberry',
  blueberry0: 'blueberry0',
  eucalyptusClassic: 'eucalyptusClassic',
  radiantEucalyptus: 'radiantEucalyptus',
  dietEucalyptus: 'dietEucalyptus',
  eucalyptus0: 'eucalyptus0',
  graphite5B: 'graphite5B',
  graphite4B: 'graphite4B',
  graphite3B: 'graphite3B',
  graphite2B: 'graphite2B',
  graphiteB: 'graphiteB',
  graphiteHB: 'graphiteHB',
  graphiteH: 'graphiteH',
  graphite2H: 'graphite2H',
  graphite3H: 'graphite3H',
  graphite4H: 'graphite4H',
  graphite5H: 'graphite5H',
} as const;
