import { Forms } from './forms.types';

export const createForms = (): Forms => ({
  fieldHeight: '2.5rem',
  fieldLineHeight: 'var(--sscds-font-lineheight-body-md);',
  toggleSize: 20,
  color: 'var(--sscds-color-text-default)',
  bgColor: 'var(--sscds-color-background-input-default)',
  disabledColor: 'var(--sscds-color-text-disabled)',
  borderColor: 'var(--sscds-color-border-input-default)',
  focusBorderColor: 'var(--sscds-color-border-input-focused)',
  invalidBorderColor: 'var(--sscds-color-border-input-error)',
  activeColor: 'var(--sscds-color-text-white)',
  activeBgColor: 'var(--sscds-color-primary-3)',
  activeBorderColor: 'var(--sscds-color-primary-9)',
  disabledBgColor: 'var(--sscds-color-background-input-disabled)',
  disabledBorderColor: 'var(--sscds-color-border-input-disabled)',
  disabledActiveColor: 'var(--sscds-color-text-subtle)',
  placeholderColor: 'var(--sscds-color-text-subtle)',
  indicatorColor: 'var(--sscds-color-icon-subtle)',
  hoverIndicatorColor: 'var(--sscds-color-icon-default)',
  hoverBgColor: 'var(--sscds-color-primary-10)',
  pressedBgColor: 'var(--sscds-color-primary-9)',
  switchBgColor: 'var(--sscds-color-neutral-3)',
  switchKnobBgColor: 'var(--sscds-color-neutral-11)',
});
